---
version: "3"
services:
  xssfastapi:
    build:
      context: "."
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    tty: true
    stdin_open: true
    restart: unless-stopped
    # init: true